### ISSUE TITLE
Incluir um campo 'codigo' em 'contrato'.

### ISSUE THREAD

**Issue by gersonkm** [cultive/siditil#11]
Discutir com o Bruno sobre a necessidade de um 'código' que facilitasse a identificação de 'contrato'. Esse código poderia ser utilizado durante a abertura de incidente para agilizar a busca um contrato.

**Comment by brunovfarias** [comment]
Essa discussão levou a alterações importantes no nosso modelo. Estas alterações contemplaram a discussão deste código que se transformou no numero que utilizamos para contato com os fornecedores. Este numero pode ser o telefone ou código net, por exemplo.
